<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="actuation_system" params="prefix base_length base_width base_height">
    <!-- Constants for robot dimensions -->
    <xacro:property name="actuator_mass" value="0.2" />
    <xacro:property name="actuator_length" value="0.1" />
    <xacro:property name="actuator_width" value="0.03" />
    <xacro:property name="actuator_height" value="0.03" />

    <!-- Actuator Joints and Links -->
    <xacro:macro name="actuator" params="id parent_link x y z">
      <joint name="${prefix}actuator_joint_${id}" type="continuous">
        <parent link="${parent_link}"/>
        <child link="${prefix}actuator_link_${id}"/>
        <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <dynamics damping="0.1"/>
        <limit effort="100" velocity="10.0"/>
      </joint>

      <link name="${prefix}actuator_link_${id}">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${actuator_length} ${actuator_width} ${actuator_height}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${actuator_length} ${actuator_width} ${actuator_height}"/>
          </geometry>
          <material name="red"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="${actuator_mass}"/>
          <inertia
            ixx="${actuator_mass / 12.0 * (actuator_width*actuator_width + actuator_height*actuator_height)}" 
            ixy="0.0" 
            ixz="0.0"
            iyy="${actuator_mass / 12.0 * (actuator_length*actuator_length + actuator_height*actuator_height)}" 
            iyz="0.0"
            izz="${actuator_mass / 12.0 * (actuator_length*actuator_length + actuator_width*actuator_width)}"/>
        </inertial>
      </link>
    </xacro:macro>

    <!-- Create 4 actuators -->
    <xacro:actuator id="0" parent_link="${prefix}base_link" x="${-base_length/4}" y="${-base_width/2}" z="${base_height/2}"/>
    <xacro:actuator id="1" parent_link="${prefix}base_link" x="${base_length/4}" y="${-base_width/2}" z="${base_height/2}"/>
    <xacro:actuator id="2" parent_link="${prefix}base_link" x="${-base_length/4}" y="${base_width/2}" z="${base_height/2}"/>
    <xacro:actuator id="3" parent_link="${prefix}base_link" x="${base_length/4}" y="${base_width/2}" z="${base_height/2}"/>

  </xacro:macro>

</robot>